	<div>&nbsp;</div>
	<div id="levels" class="btn-toolbar" role="toolbar">
		<div class="btn-group" role="group">
			<a id="easy"   type="button" class="btn btn-default">Easy</a>
			<a id="medium" type="button" class="btn btn-default">Medium</a>
			<a id="hard"   type="button" class="btn btn-default">Hard</a>
			<a id="expert" type="button" class="btn btn-default">Expert</a>
		</div>
		<div class="btn-group" role="group">
			<a id="optim"    type="button" class="btn btn-default">Optimisation</a>
			<a id="codegolf" type="button" class="btn btn-default">Code golf</a>
		</div>
		<!--
		<div class="btn-group" role="group">
			<a id="community" type="button" class="btn btn-default">Community</a>
		</div>
		-->
	</div>